name: Docker Build, Security Scan, and Terraform Plan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Add this to allow manual trigger

jobs:
  # Step 1: Build Docker image
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Save Docker image as artifact
        run: docker save my-docker-image | gzip > my-docker-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: my-docker-image.tar.gz

  # Step 2: Docker Image Security Scan with Trivy
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: build-docker-image  # Ensure Docker image is built first
    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Load Docker image
      run: gunzip -c my-docker-image.tar.gz | docker load

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-docker-image'

  # Step 3: Run Terraform Plan
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'eu-west-1'
    needs: trivy-scan  # Wait for Docker scan to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Run Terraform Init and Plan
      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=plan.tfplan

      # Convert Terraform Plan to JSON and Run Checkov
      - name: Terraform Show (convert plan to JSON)
        run: |
          cd terraform
          terraform show -json plan.tfplan > plan.tfplan.json


      # Upload plan.tfplan.json as an artifact
      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-json
          path: terraform/plan.tfplan.json

  # Step 4: Checkov Scan
  checkov-scan:
    name: Checkov Scan
    runs-on: ubuntu-latest
    needs: terraform-plan  # Wait for Terraform Plan to complete
    steps:
      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan-json

      # Install Checkov
      - name: Install Checkov
        run: pip install checkov

      # Run Checkov scan on the downloaded Terraform plan JSON
      - name: Run Checkov scan
        run: checkov -f terraform/plan.tfplan.json || true
  
  # Step 5: TFSEC Scan
  tfsec-scan:
    name: TFSEC Scan
    runs-on: ubuntu-latest
    needs: checkov-scan
    env:
      TFSEC_VERSION: '1.28.1' 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Install tfsec'
        run: |
          curl -Lo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
          chmod +x tfsec
          mv tfsec /usr/local/bin/
          tfsec --version
  
      - name: 'tfsec'
        run: |
          cd terraform
          tfsec .
          
 # Step 6: Manual Deployment (Terraform Apply)
  terraform-apply:
    name: Terraform Apply (Manual Step)
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'eu-west-1'  
    needs: tfsec-scan
    if: github.event_name == 'workflow_dispatch'  # Ensure this only runs manually
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply --auto-approve