name: Docker Build, Security Scan, and Terraform Plan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Add this to allow manual trigger

jobs:
  # Step 1: Build Docker image
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-docker-image .
      - name: Save Docker image as artifact
        run: docker save my-docker-image | gzip > my-docker-image.tar.gz
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: my-docker-image.tar.gz

  # Step 2: Docker Image Security Scan with Trivy
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: build-docker-image  # Ensure Docker image is built first
    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: docker-image
    - name: Load Docker image
      run: gunzip -c my-docker-image.tar.gz | docker load
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-docker-image'

  # Step 3: Run Terraform Plan and Checkov Scan
  terraform-setup:
    name: Terraform Plan and Security Scan
    runs-on: ubuntu-latest
    needs: trivy-scan  # Wait for Docker scan to complete
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Terraform and Checkov
      - name: Install Terraform and Checkov
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO "https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip"
          unzip terraform_1.5.2_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
          pip install checkov

      # Run Terraform Init and Plan
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      # Convert Terraform Plan to JSON and Run Checkov
      - name: Terraform Show (convert plan to JSON)
        run: terraform show -json plan.tfplan > plan.tfplan.json

      - name: Run Checkov scan on Terraform plan
        run: checkov -f plan.tfplan.json

 # Step 4: Manual Deployment (Terraform Apply)
  terraform-apply:
    name: Terraform Apply (Manual Step)
    runs-on: ubuntu-latest
    needs: terraform-setup
    if: github.event_name == 'workflow_dispatch'  # Ensure this only runs manually
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: terraform apply --auto-approve